### ISSUE TITLE
[1.18.1] Treasure Chest lags with Map inside

### ISSUE THREAD

**Issue by pewblaze** [Aureljz/Buried-Barrels#3]
So i updated the mod & after testing the loot chests i recognized a really big lag when a buried barrel map is inside.
Its fine if there isnt a treasure map inside. Also without the mod it works fine.

/give pewblaze minecraft:chest{BlockEntityTag:{LootTable:"chests/jungle_temple"}}

I tested it with the jungle chest. 
Am i the only one? ^^"

**Comment by Aureljz** [comment]
This is a vanilla issue I can't directly fix. There's usually brief TPS lag spikes when generating exploration maps, even when using cartographers, due to the task of charting an area to create the actual map.
